# Generated by Django 2.2.7 on 2020-01-28 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_username', models.CharField(max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
                ('num_followers', models.IntegerField(default=0)),
                ('num_following', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_followers', to='followtracker.User')),
            ],
        ),
        migrations.CreateModel(
            name='Followee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_followees', to='followtracker.User')),
            ],
        ),
    ]
