# Generated by Django 2.2.7 on 2020-01-31 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followtracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_followed',
        ),
    ]
