# Generated by Django 2.2.7 on 2020-02-06 03:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('followtracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_update_ts',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
