# Generated by Django 2.2.7 on 2020-01-30 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followtracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='num_following',
            new_name='num_followees',
        ),
    ]
