# Generated by Django 2.2.7 on 2020-02-12 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('followtracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowerWithCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('num_followers', models.IntegerField(default=0)),
                ('create_ts', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_follower_with_count', to='followtracker.InstaUser')),
            ],
        ),
    ]
