# Generated by Django 2.2.7 on 2020-02-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followtracker', '0002_followerwithcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='num_followers',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='FollowerWithCount',
        ),
    ]
