# Generated by Django 2.2.7 on 2020-02-07 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('followtracker', '0002_user_last_update_ts'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
                ('num_followers', models.IntegerField(default=0)),
                ('num_followees', models.IntegerField(default=0)),
                ('create_ts', models.DateTimeField(auto_now_add=True)),
                ('last_update_ts', models.DateTimeField(auto_now_add=True)),
                ('receiving_weekly_updates', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='followee',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_followees', to='followtracker.InstaUser'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_followers', to='followtracker.InstaUser'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
