# Generated by Django 2.2.7 on 2020-02-10 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followtracker', '0003_auto_20200207_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instauser',
            name='receiving_weekly_updates',
        ),
    ]
