# Generated by Django 2.2.7 on 2020-03-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followtracker', '0003_auto_20200213_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='instauser',
            name='get_emails',
            field=models.BooleanField(default=0),
        ),
    ]
